### PR TITLE
Upgrade all dependencies

### PR DESCRIPTION
**Pull request by lbineau**
There are a lot of security issues raised by this package so I've upgraded all dependencies.
Only `chai` packages couldn't be upgraded to the latest `major` version because it is using ESM. I only sticked with the latest `minor` version.
I've `npm run test` and `npm run build` and everything seems to work.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, could you also bump the patch version of the package?

**Comment by Naramsim** [comment]
Thanks!

**Comment by Naramsim** [comment]
Hi! A user seems to have a problem with this version 1.2.5, @isackender. Coul it be possible that the package is broken?

Preventively I unpublished the 1.2.5 from NPM. Still the lib can be found in this GH repo under the `dist` folder.

**Comment by isackender** [comment]
Hi, yes, as @Naramsim pointed out, my project broke two days ago. My code is:

```
<script src="https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js"></script>

<!-- Service worker on root of project -->
<script src="pokeapi-js-wrapper-sw.js"></script>

<!-- Initialize js wrapper -->
<script>
    const customOptions = {
        protocol: "https",
        versionPath: "/api/v2/",
        cache: true,
        timeout: 5 * 1000, // 5s
        cacheImages: true
    };
    const P = new Pokedex.Pokedex(customOptions);
</script>

<!-- Project code -->
<script src="/scripts/script.js"></script>
```

Which gives me this error:
```
Uncaught ReferenceError: require is not defined
    23          https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    n           https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    801         https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    n           https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    737         https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    n           https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
    <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
index.js:2:61271
```


When I switch to version 1.2.3 it works again perfectly.
```
<script src="https://unpkg.com/pokeapi-js-wrapper@1.2.3/dist/index.js"></script>
```

**Comment by climaxmba** [comment]
> Hi, yes, as @Naramsim pointed out, my project broke two days ago. My code is:
> 
> ```
> <script src="https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js"></script>
> 
> 
> <script src="pokeapi-js-wrapper-sw.js"></script>
> 
> 
> <script>
>     const customOptions = {
>         protocol: "https",
>         versionPath: "/api/v2/",
>         cache: true,
>         timeout: 5 * 1000, // 5s
>         cacheImages: true
>     };
>     const P = new Pokedex.Pokedex(customOptions);
> </script>
> 
> 
> <script src="/scripts/script.js"></script>
> ```
> 
> Which gives me this error (using Firefox):
> 
> ```
> Uncaught ReferenceError: require is not defined
>     23          https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     n           https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     801         https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     n           https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     737         https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     n           https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
>     <anonymous> https://unpkg.com/pokeapi-js-wrapper@1.2.5/dist/index.js:2
> index.js:2:61271
> ```
> 
> When I switch to a previous version it works again perfectly (1.2.3 or 1.2.4 work fine).
> 
> ```
> <script src="https://unpkg.com/pokeapi-js-wrapper@1.2.3/dist/index.js"></script>
> ```

I've seen something like this when I was using a React package. Uninstalling or downgrading the broken dependency in this package should fix that.

**Comment by Naramsim** [comment]
I remember I had issues upgrading axios, because maybe it became a pure ESM package. Maybe that's the issue

**Comment by climaxmba** [comment]
Sure, this package is meant for the browser only. There is another package for node.

**Comment by lbineau** [comment]
Here you go https://github.com/PokeAPI/pokeapi-js-wrapper/pull/61

**Pull request merged**
