### PR TITLE
Bugfix/axios webpack require

### PR DESCRIPTION
**Pull request by lbineau**
The previous PR https://github.com/PokeAPI/pokeapi-js-wrapper/pull/58 introduced issues with the built file.
This PR aim to fix this issue by changing the webpack target from `node` to `web` which was wrongly configured and probably worked because of node polyfill included by default: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

I've `npm run test` and `npm run build`, and everything seems to work. Then I included the built file locally in an `index.html` file and no more error are shown.

**Error `target: 'node'`**
node target showing a console error: require is undefined

**Success `target: 'web'`**
web target showing a console.log success

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi! Thanks for the pr! Would it be possible to use a beta tag for this release? If we have positive feedback we will promote the code to a normal release

**Comment by lbineau** [comment]
@Naramsim Sure, can you explain me how to do this?

**Comment by Naramsim** [comment]
I should be able to do it according to the docs: https://docs.npmjs.com/adding-dist-tags-to-packages

So no action on your side

**Comment by Naramsim** [comment]
ok, I think I published the `pokeapi-js-wrapper@beta` version. 

https://www.npmjs.com/package/pokeapi-js-wrapper?activeTab=versions

@isackender , could you try and install that version?

**Comment by climaxmba** [comment]
> ok, I think I published the `pokeapi-js-wrapper@beta` version.
> 
> https://www.npmjs.com/package/pokeapi-js-wrapper?activeTab=versions
> 
> @isackender , could you try and install that version?

@Naramsim, I just tried that and it works just fine. Here is a live demo: [https://climaxmba.github.io/memory-card/](https://climaxmba.github.io/memory-card/). And the repo: [https://github.com/climaxmba/memory-card](https://github.com/climaxmba/memory-card)

**Comment by isackender** [comment]
Thanks @lbineau @Naramsim @climaxmba 
Version 1.2.6 works perfectly now! :)

**Pull request merged**
