### PR TITLE
Added a retry fetch without "/" if the origin is failed.

### PR DESCRIPTION
**Pull request by shinymimiq**
People will encounter errors when "/" present at the end of url. According to pokeapi it is something related to Cloudflare. 
Added a retry to workaround it.

### CODE REVIEW

**Comment by shinymimiq** [comment]
Hmmm, not quite sure how to fix the coverage checks, any suggestion?

**Comment by Naramsim** [comment]
@shinymimiq We fixed the issue at pokeAPI. I don't know if we still need it. Anyway I'll take a look at your PR later and let you know what I think 😄 

Thanks for the contrib!

**Comment by shinymimiq** [comment]
Oh cool, I didn't realise it has been fixed. If you don't think this patch is need any more please just close it 😄

**Comment by Naramsim** [comment]
@shinymimiq I thought about it and I don't think it's necessary this logic anymore. 

Also, about returning the retried request in the `.catch()` block, I think the end-user would get the correct result inside an error

**Comment by shinymimiq** [comment]
Thanks. I'll close the PR.

**Pull request closed without merging**
